AWSTemplateFormatVersion: '2010-09-09'
Description: 'ACM Certificate for Custom Domain (CloudFront - us-east-1 only)'

Parameters:
  DomainName:
    Type: String
    Description: The apex domain name

  SubDomain:
    Type: String
    Description: Subdomain prefix

  HostedZoneId:
    Type: String
    Description: Route 53 Hosted Zone ID

Resources:
  # ACM Certificate
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub '${SubDomain}.${DomainName}'
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Sub '${SubDomain}.${DomainName}'
          HostedZoneId: !Ref HostedZoneId
      Tags:
        - Key: Name
          Value: !Sub '${SubDomain}.${DomainName}'

Outputs:
  CertificateArn:
    Description: ACM Certificate ARN
    Value: !Ref Certificate
